SAD/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("accounts.urls", namespace='account')),
    path('', include("medical.urls", namespace='medical')),
    path('', include("order_billing.urls", namespace='billing')),
    path('', include('medical.REST.urls', namespace='api')),
    path('', include('accounts.REST.urls', namespace='rest')),
    path('ckeditor/', include('ckeditor_uploader.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('patient/<username>', views.getPatient.as_view(), name="patient"),
    path('update', views.getUpdate.as_view(), name="update_patient"),
    path('register/', views.getRegister.as_view(), name="register"),
    path('account/create', views.getAccountCreate.as_view(), name="account_create"),
    path('login/', views.getLogin.as_view(), name="login"),
    path('shipping/create', views.CreateShipping.as_view(), name="shipping_create"),
    path('shipping/update', views.updateShipping, name="shipping_update"),
    path('changepass/', views.changePass.as_view(), name="changepass"),
    path('account/delete', views.deleteAccount.as_view(), name="delete_account"),
    path('logout/', views.getLogout, name="logout"),



    path('activate/<uid>/<token>',views.activate, name='activate'),
]

medical/REST/urls.py
from django.urls import path
from medical.REST.views import (
    #Hospital API URLs Mapping
    HospitalListApi,
    HospitalCreateApi,
    HospitalRetrieveApi,
    HospitalUpdateApi,
    HospitalDeleteApi,

    #Test API URLs Mapping
    HasTestListAPI,
    HasTestCreateAPI,
    HasTestReadAPI,
    HasTestUpdateAPI,
    HasTestDeleteAPI,

    # Package API URLs Mapping
    PackageListApi,
    PackageCreateApi,
    PackageRetrieveApi,
    PackageUpdateAPI,
    PackageDeleteAPI
)
app_name = "medical"


urlpatterns = [
    path('api/hospitals/', HospitalListApi.as_view(), name="hospitals"),
    path('api/hospital/create', HospitalCreateApi.as_view(), name="create"),
    path('api/hospital/<int:id>', HospitalRetrieveApi.as_view(), name="hospital"),
    path('api/hospital/update/<int:id>', HospitalUpdateApi.as_view(), name="update"),
    path('api/hospital/delete/<int:id>', HospitalDeleteApi.as_view(), name="delete"),

    #Has_test API URLs
    path('api/tests', HasTestListAPI.as_view(), name="tests"),
    path('api/test/create', HasTestCreateAPI.as_view(), name="create_test"),
    path('api/test/<int:id>', HasTestReadAPI.as_view(), name="read_test"),
    path('api/test/update/<int:id>', HasTestUpdateAPI.as_view(), name="update_test"),
    path('api/test/delete/<int:id>', HasTestDeleteAPI.as_view(), name="delete_test"),


    # Packages API URLs
    path('api/packages', PackageListApi.as_view(), name="packages"),
    path('api/package/create', PackageCreateApi.as_view(), name="create_package"),
    path('api/package/<int:id>', PackageRetrieveApi.as_view(), name="read_package"),
    path('api/package/update/<int:id>', PackageUpdateAPI.as_view(), name="update_package"),
    path('api/package/delete/<int:id>', PackageDeleteAPI.as_view(), name="delete_package")
]

medical/urls.py
from django.urls import path
from . import views

app_name="medical"

urlpatterns = [
    path('', views.index.as_view(), name="index"),
    path('tests/', views.getTests.as_view(), name="all_test"),
    path('test/<int:id>', views.getSingleTest.as_view(), name="signle_test"),
    path('details/<int:has_test_id>', views.testDetails.as_view(), name="test_details"),
    path('packages', views.testPackages.as_view(), name="test_packages"),
    path('package/<int:id>', views.singlePackage.as_view(), name="package_details"),
    path('hospitals', views.getHospitals.as_view(), name="all_hospitals"),
    path('hospital/<int:id>', views.singleHospital.as_view(), name="hospital_details"),
    path('search', views.search.as_view(), name="search"),




    # Authorized hospital url mapping
    path('author', views.getLoggedHospital.as_view(), name="logged_hospital"),
    path('author/test', views.ViewTestByHospital.as_view(), name="authorize_tests"),
    path('author/test/add', views.AuthorTestAdd.as_view(), name="authorize_test_add"),
    path('author/test/update/<int:id>', views.AuthorTestUpdate, name="authorize_test_update"),
    path('author/package', views.AuthorViewPackage.as_view(), name="authorize_package_view"),
    path('author/package/add', views.AuthorAddPackage.as_view(), name="authorize_package_add"),
    path('author/package/update/<int:id>', views.AuthorPackageUpdate, name="authorize_package_update"),
    path('author/package/item/add/<int:id>', views.AuthorPackItemAdd.as_view(), name="authorize_package_item_add"),
    path('author/package/item/update/<int:id>', views.AuthorPackItemEdit, name="authorize_package_item_update"),

    path('author/test/orders', views.AuthorTestOrder.as_view(), name="authorize_order"),
    path('author/package/orders', views.AuthorPackageOrder.as_view(), name="authorize_package_order"),
    path('author/test/order/<int:id>', views.AuthorTestSingleOrder.as_view(), name="authorize_single_order"),
    path('author/package/order/<int:id>', views.AuthorPackageSingleOrder.as_view(), name="authorize_package_single_order"),
    path('author/test/order/update/<int:id>', views.AuthorTestOrderUpdate, name="authorize_single_order_update"),
    path('author/package/order/update/<int:id>', views.AuthorPackageOrderUpdate, name="authorize_package_order_update"),



    # Archive pages

    path('author/test/orders/archive', views.AuthorTestOrderArchived.as_view(), name="authorize_test_order_archive"),
    path('author/package/orders/archive', views.AuthorPackageOrderArchived.as_view(), name="authorize_package_order_archive"),


    # Feedback and reviews urls mapping

    path('author/feedback', views.AuthorFeedback.as_view(), name="feedback"),
    path('author/review', views.AuthorReview.as_view(), name="review"),

    #REST API Home page url
    path('api', views.ApiHome.as_view(), name='api_home')
]

order_billing/urls.py
from django.urls import path
from . import views

app_name="order_billing"

urlpatterns = [
    path("order/test/<int:id>", views.getTestOrder.as_view(), name="order"),
    path('delete/test/<int:pk>', views.deleteTestOrder.as_view(), name="delete"),
    path('payment/test/<int:id>',views.testPayments.as_view(), name="payment"),
    path('payment/test/update/<int:id>', views.updateTestPayment, name="update_payment"),
    path('test/form/<int:id>', views.generateTestForm.as_view(), name="generate_form"),

    path('order/package/<int:id>', views.getPackageOrder.as_view(), name="package_order"),
    path('delete/package/<int:id>', views.deletePackageOrder.as_view(), name="delete_package_order"),
    path('payment/package/<int:id>', views.packagePayments.as_view(), name="package_payment"),
    path('payment/package/update/<int:id>', views.updatePackagePayment, name="update_package_payment"),
    path('package/form/<int:id>', views.generatePackageForm.as_view(), name="generate_package_form")
]

templates/api.html
{% extends 'base.html' %}
{% block title %}Virtual medical assistant API{% endblock %}
{% block stylesheet %}
    <style>
    .main-content {
    margin-top: 100px;
    }
    nav{
    background-color: #1C2331!important;
    }
    .row div{
        margin-top: 5px;
    }
    </style>
{% endblock %}
{% block content %}
    <div class="main-content">
        <div class="container">
            <div class="breadcrumbs">
                <div class="bc-icons-2">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a class="black-text" href="{% url 'medical:index' %}">Home</a><i class="fa fa-caret-right mx-2" aria-hidden="true"></i></li>
                        <li class="breadcrumb-item">API</li>
                    </ol>
                </div>
            </div>
            <!--Breadcrumbs-->
            <div class="row">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header deep-orange lighten-1 white-text">Hospital</div>
                        <div class="card-body">
                            <ul>
                                <li><a href="{% url 'api:hospitals' %}">View Hospital API</a></li>
                                <li><a href="{% url 'api:create' %}">Create Hospital API</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header deep-orange lighten-1 white-text">Diagnostic Test</div>
                        <div class="card-body">
                            <ul>
                                <li><a href="{% url 'api:tests' %}">Test View API</a></li>
                                <li><a href="{% url 'api:create_test' %}">Create Test API</a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header deep-orange lighten-1 white-text">Package</div>
                        <div class="card-body">
                            <ul>
                                <li><a href="{% url 'api:packages' %}">View Package API</a></li>
                                <li><a href="{% url 'api:create_package' %}">Create Package API</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header deep-orange lighten-1 white-text">Shipping</div>
                        <div class="card-body">
                            <ul>
                                <li><a href="{% url 'rest:shipping' %}">Shipping API</a></li>
                                <li><a href="{% url 'rest:shipping_create' %}">Shipping Create API</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header deep-orange lighten-1 white-text">Patient</div>
                        <div class="card-body">
                            <ul>
                                <li><a href="{% url 'rest:patient' %}">Patient View API</a></li>
                                <li><a href="{% url 'rest:patient_create' %}">Patient Create API</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-6"></div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script>
    $(document).ready(function() {
        $('.api').addClass('active');
    });
    </script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}
    {% endblock %}</title>
    <!-- Font Awesome -->
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    {% load staticfiles %}
    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static "css/mdb.min.css" %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static "css/style.min.css" %}" rel="stylesheet">
    <style>
    a.nav-link.dropdown-toggle.waves-effect.waves-light {
    color: white;
    }
    body{
    font-family: 'Raleway', sans-serif;
    }
    div.datas{
    border: 1px solid #ded6d6;
    box-shadow: 1px 1px 6px 2px #ccc;
    padding: 5px;
    }
    div#example_wrapper {
    margin-top: 5px;
    }
    .thead, .ttitle, .tdetails {
    border-bottom: 1px solid #d4caca;
    padding: 20px;
    }
    select.form-control:not([size]):not([multiple]) {
        height: auto;
    }

    {#Breadcrumbs css#}
    .bc-icons-2 .breadcrumb-item + .breadcrumb-item::before {
    content: none; }
    .bc-icons-2 .breadcrumb-item.active {
    color: #455a64; }
    /*Style For Browser Scrollbar*/
    /* width */
    ::-webkit-scrollbar {
        width: 10px;
    }

    /* Track */
    ::-webkit-scrollbar-track {
        background: lightblue;
    }

    /* Handle */
    ::-webkit-scrollbar-thumb {
        background: lightgray;
    }

    /* Handle on hover */
    ::-webkit-scrollbar-thumb:hover {
      background: #297e0f;
    }
    </style>


    {% block stylesheet %}
    {% endblock %}
  </head>
  <body>
    <!-- Navbar -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark scrolling-navbar">
      <div class="container">
        <!-- Brand -->
        <a class="navbar-brand" href="{% url 'medical:index' %}">
          <strong>VMA</strong>
        </a>
        <!-- Collapse -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Left -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item test">
              <a class="nav-link" href="{% url 'medical:all_test' %}">Diagnostic Tests
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item package">
              <a class="nav-link" href="{% url 'medical:test_packages' %}">Test Packages</a>
            </li>
            <li class="nav-item hospital">
              <a class="nav-link" href="{% url 'medical:all_hospitals' %}">Hospitals</a>
            </li>
            <li class="nav-item api">
              <a class="nav-link" href="{% url 'medical:api_home' %}">API</a>
            </li>
          </ul>
          <!-- Right -->
          <ul class="navbar-nav">
            {% if request.user.is_authenticated %}
              <!-- Basic dropdown -->
              <li class="btn-group">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ request.user.username|title }}</a>
                <div class="dropdown-menu">
                  {% if request.session.hospital %}
                    <a class="dropdown-item" href="{% url 'medical:logged_hospital' %}">Dashboard</a>
                  {% else %}
                    <a class="dropdown-item" href="{% url 'accounts:patient' username=request.user.username %}">Profile</a>
                  {% endif %}
                  <a class="dropdown-item" href="#">Setting</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
                </div>
              </li>
            {% else %}
              <li class="nav-item login">
                <a href="{% url 'accounts:login' %}" class="nav-link">
                  <i class="fa fa-sign-in" aria-hidden="true"></i>Login
                </a>
              </li>
            {% endif %}
            <li class="nav-item">
              <form action="{% url 'medical:search' %}" method="get">
                <input type="text" name="q" value="{{ request.GET.q }}" class="form-control" id="nav-search" placeholder="Search test" style="background: transparent; color: #fff3cd;">
              </form>
            </li>
            {% if request.user.is_authenticated %}
              {% if request.user.is_active and request.user.is_superuser %}
                <li class="nav-item">
                  <a href="/admin" class="nav-link">Dashboard</a>
                </li>
              {% endif %}
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <!-- Navbar -->
    {% block content %}
    {% endblock %}
    <!--Footer-->
    <footer class="page-footer text-center font-small mt-4 wow fadeIn">
      <hr class="my-4">
      <!-- Social icons -->
      <div class="pb-4">
        <a href="#" target="_blank">
          <i class="fa fa-facebook mr-3"></i>
        </a>
        <a href="#" target="_blank">
          <i class="fa fa-twitter mr-3"></i>
        </a>
        <a href="#" target="_blank">
          <i class="fa fa-youtube mr-3"></i>
        </a>
        <a href="#" target="_blank">
          <i class="fa fa-google-plus mr-3"></i>
        </a>
        <a href="#" target="_blank">
          <i class="fa fa-dribbble mr-3"></i>
        </a>
        <a href="#" target="_blank">
          <i class="fa fa-pinterest mr-3"></i>
        </a>
        <a href="#" target="_blank">
          <i class="fa fa-github mr-3"></i>
        </a>
        <a href="#" target="_blank">
          <i class="fa fa-codepen mr-3"></i>
        </a>
      </div>
      <!-- Social icons -->
      <!--Copyright-->
      <div class="footer-copyright py-3">
        © 2018 Copyright:
        <a href="https://fb.com/404detector" target="_blank"> Saimoon, Naeem, Ahsan, Nasir </a>
      </div>
      <!--/.Copyright-->
    </footer>
    <!--/.Footer-->
    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
    <!-- Initializations -->
    <script type="text/javascript">
    // Animations initialization
    new WOW().init();
    </script>
    {% block script %}
    {% endblock %}
  </body>
</html>

templates/patient.html
{% extends 'base.html' %}
{% block title %}
    {{ user.username }}
{% endblock %}
{% block stylesheet %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/jquery.dynatable.css' %}">
    <style>
    .main-content {
    margin-top: 100px;
    }
    nav{
    background-color: #1C2331!important;
    }
    .links {
    border: 0.05em solid #c1cce8;
    padding: 10px;
    box-shadow: 3px 2px 3px lightgrey;
    }
    th a{
    color: white!important;
    text-decoration: underline;
    }
    th{background: #006a72;}
    .bought-test {
    border: 1px solid lightblue;
    margin-top: 50px;
}
    div.bought-test h4{
        background: linear-gradient(#61bedc, #046c8e);
        color: white;
        padding: 10px;
    }
    </style>
{% endblock %}
{% block content %}
    <div class="main-content">
        <div class="container wow fadeIn">
            {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                        <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
                    {% endfor %}
                </div>
            {% endif %}
            <div class="row">
                <div class="col-md-4">
                    <div class="pr-image">
                        <img src="{{ patient.image.url }}" alt="" height="300" style="max-width: 375px;">
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="row">
                        <div class="col-4">Name: </div>
                        <div class="col-8">{{ user.username }}</div>
                    </div>
                    <div class="row">
                        <div class="col-4">Phone: </div>
                        <div class="col-8">{{ patient.phone }}</div>
                    </div>
                    <div class="row">
                        <div class="col-4">Email: </div>
                        <div class="col-8">{{ user.email }}</div>
                    </div>
                    <div class="row">
                        <div class="col-4">Height: </div>
                        <div class="col-8">{{ patient.height }}</div>
                    </div>
                    <div class="row">
                        <div class="col-4">Weight: </div>
                        <div class="col-8">{{ patient.weight }} KG</div>
                    </div>
                    <div class="row">
                        <div class="col-4">Sex: </div>
                        <div class="col-8">{{ patient.sex }}</div>
                    </div>
                    <div class="row">
                        <div class="col-4">Is smoker: </div>
                        <div class="col-8">{{ patient.smoker }}</div>
                    </div>
                    <div class="links">
                        <div class="row">
                            <div class="col-6"><a href="{% url 'accounts:update_patient' %}">Update info</a></div>
                            {% if shipping %}
                                <div class="col-6"><a href="{% url 'accounts:shipping_update' %}">Update shipping info</a></div>
                                {% else %}
                                <div class="col-6"><a href="{% url 'accounts:shipping_create' %}">Add shipping info</a></div>
                            {% endif %}
                            <div class="col-6"><a href="{% url 'account:changepass' %}">Change password</a></div>
                            <div class="col-6"><a href="{% url 'accounts:delete_account'%}">Delete account</a></div>
                            <div class="col-6"><a href="{% url 'accounts:logout' %}">Log out</a></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="bought-test">
                <h4>Test are bought by this patient</h4>
                <table id="my-table" class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Bill</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for test in tests %}
                            <tr>
                                <td>{{ test.test.name.name }}</td>
                                <td>{{ test.test.price }}</td>
                                <td><a href="{% url 'order_billing:order' id=test.id %}"><i class="fa fa-eye fa-2x"></i></a>  <a href="{% url 'order_billing:delete' pk=test.id %}"><i class="fa fa-trash fa-2x"></i></a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="bought-test">
                <h4>Packages are bought by this patient</h4>
                <table id="pkg-table" class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Bill</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for pack in package %}
                            <tr>
                                <td>{{ pack.package_name.name }}</td>
                                <td>{{ pack.package_name.price }}</td>
                                <td><a href="{% url 'order_billing:package_order' id=pack.id %}"><i class="fa fa-eye fa-2x"></i></a>  <a href="{% url 'order_billing:delete_package_order' id=pack.id %}"><i class="fa fa-trash fa-2x"></i></a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script src="{% static 'js/jquery.dynatable.js' %}"></script>
    <script>
    $('#my-table').dynatable({
    table: {
    defaultColumnIdStyle: 'trimDash'
    }
    });
    $('#pkg-table').dynatable({
    table: {
    defaultColumnIdStyle: 'trimDash'
    }
    });
    </script>
{% endblock %}

templates/sample.html
{% extends 'base.html' %}
{% block title %}{% endblock %}
{% block stylesheet %}
    <style>
    .main-content {
    margin-top: 100px;
    }
    nav{
    background-color: #1C2331!important;
    }
    </style>
{% endblock %}
{% block content %}
    <div class="main-content">
        <div class="container">
            <div class="breadcrumbs">
                <div class="bc-icons-2">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a class="black-text" href="{% url 'medical:index' %}">Home</a><i class="fa fa-caret-right mx-2" aria-hidden="true"></i></li>
                        <li class="breadcrumb-item">Packages</li>
                    </ol>
                </div>
            </div>
            <!--Breadcrumbs-->
        </div>
    </div>
{% endblock %}
{% block script %}
{% endblock %}

templates/single_package.html
{% extends 'base.html' %}
{% block title %}Package: {{ package.name }}{% endblock %}
{% block stylesheet %}
    <style>
    .main-content{
    margin-top: 100px;
    }
    nav{
    background-color: #1C2331!important;
    }
    .package-details, .hospital-details {
    border: 1px solid #d6dedd;
    box-shadow: 3px 2px 3px 1px #c1eaf7;
    margin-bottom: 10px;
    }
    .package-header .row, .package-body, .package-items, .hospital-header, .hospital-info{
    padding: 10px;
    }
    .package-header, .hospital-header {
    background: linear-gradient(#fbfafa, #daf1f7);
    }
    </style>
{% endblock %}
{% block content %}
    <div class="main-content">
        <div class="container">
            <div class="breadcrumbs">
                <div class="bc-icons-2">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a class="black-text" href="{% url 'medical:index' %}">Home</a><i class="fa fa-caret-right mx-2" aria-hidden="true"></i></li>
                        <li class="breadcrumb-item"><a class="black-text" href="{% url 'medical:test_packages' %}">Packages</a><i class="fa fa-caret-right mx-2" aria-hidden="true"></i></li>
                        <li class="breadcrumb-item">{{ package.name }}</li>
                    </ol>
                </div>
            </div>
            <!--Breadcrumbs-->
            <div class="single-package">
                <div class="package-details">
                    <div class="package-header">
                        <div class="row">
                            <div class="col-md-8">
                                <h3>Package: {{ package.name }}</h3>
                            </div>
                            <div class="col-md-4">
                                <h5>Price: {{ package.price }}‎৳</h5>
                            </div>
                        </div>
                    </div>
                    <div class="package-body">
                        <p>{{ package.details|safe }}</p>
                    </div>
                    <div class="package-items">
                        <h4 class="">Package Items</h4>
                        <hr>
                        <ul>
                            {% for item in items %}
                                {% for i in item.test.all %}
                                    <li>{{ i }}</li>
                                    {% empty %}
                                    <h1>Sorry! No items found</h1>
                                {% endfor %}
                                {% empty %}
                                <h1>Sorry! No items found</h1>
                            {% endfor %}
                        </ul>
                        <div class="cart-btn text-center">
                            <div class="row">
                                <div class="col-md-6"></div>
                                <div class="col-md-6">
                                    {% if request.user.is_authenticated %}
                                        {% if request.session.hospital %}
                                            {% if request.session.hospital == package.hospital.name.username %}
                                                <a href="{% url 'medical:authorize_package_update' id=package.id %}" class="btn btn-outline-dark">Update package</a>
                                            {% endif %}
                                            {% else %}
                                            {% if is_bought %}
                                                <a href="{% url 'order_billing:package_order' id=orderId %}" class="btn btn-cyan">View order</a>
                                                <p class="text-muted">You already ordered for this package</p>
                                            {% else %}
                                                <form action="" method="POST">
                                                    {% csrf_token %}
                                                    <button class="btn btn-primary">Buy now</button>
                                                </form>
                                            {% endif %}
                                        {% endif %}
                                    {% else %}
                                        <a href="{% url 'accounts:login' %}?next={% url 'medical:package_details' id=package.id %}" class="btn btn-primary">Buy Now</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="hospital-details">
                    <h3 class="hospital-header">Hospital info:</h3>
                    <div class="row">
                        <div class="col-md-5">
                            <div class="hospital-info">
                                <p>Name: {{ package.hospital.name.get_full_name }}</p>
                                <p>Type: {{ package.hospital.type }}</p>
                                <p>Email: {{ package.hospital.email }}</p>
                                <p>Phone: {{ package.hospital.phone }}</p>
                                <p>Address: {{ package.hospital.address }}, {{ package.hospital.division }} - {{ package.hospital.zip_code }}</p>
                            </div>
                        </div>
                        <div class="col-md-7">
                            <iframe width="600" height="450" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyA43-pm17h9AYwodjdvqYMVXc3z60BaJX0&q={{ package.hospital.name.get_full_name }}" allowfullscreen></iframe>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
{% endblock %}