SAD/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("accounts.urls", namespace='account')),
    path('', include("medical.urls", namespace='medical')),
    path('', include("order_billing.urls", namespace='billing')),
    path('', include('medical.REST.urls', namespace='api')),
    path('', include('accounts.REST.urls', namespace='rest')),
    path('ckeditor/', include('ckeditor_uploader.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medical/urls.py
from django.urls import path
from . import views

app_name="medical"

urlpatterns = [
    path('', views.index.as_view(), name="index"),
    path('tests/', views.getTests.as_view(), name="all_test"),
    path('test/<int:id>', views.getSingleTest.as_view(), name="signle_test"),
    path('details/<int:has_test_id>', views.testDetails.as_view(), name="test_details"),
    path('packages', views.testPackages.as_view(), name="test_packages"),
    path('package/<int:id>', views.singlePackage.as_view(), name="package_details"),
    path('hospitals', views.getHospitals.as_view(), name="all_hospitals"),
    path('hospital/<int:id>', views.singleHospital.as_view(), name="hospital_details"),
    path('search', views.search.as_view(), name="search"),




    # Authorized hospital url mapping
    path('author', views.getLoggedHospital.as_view(), name="logged_hospital"),
    path('author/test', views.ViewTestByHospital.as_view(), name="authorize_tests"),
    path('author/test/add', views.AuthorTestAdd.as_view(), name="authorize_test_add"),
    path('author/test/update/<int:id>', views.AuthorTestUpdate, name="authorize_test_update"),
    path('author/package', views.AuthorViewPackage.as_view(), name="authorize_package_view"),
    path('author/package/add', views.AuthorAddPackage.as_view(), name="authorize_package_add"),
    path('author/package/update/<int:id>', views.AuthorPackageUpdate, name="authorize_package_update"),
    path('author/package/item/add/<int:id>', views.AuthorPackItemAdd.as_view(), name="authorize_package_item_add"),
    path('author/package/item/update/<int:id>', views.AuthorPackItemEdit, name="authorize_package_item_update"),

    path('author/test/orders', views.AuthorTestOrder.as_view(), name="authorize_order"),
    path('author/package/orders', views.AuthorPackageOrder.as_view(), name="authorize_package_order"),
    path('author/test/order/<int:id>', views.AuthorTestSingleOrder.as_view(), name="authorize_single_order"),
    path('author/package/order/<int:id>', views.AuthorPackageSingleOrder.as_view(), name="authorize_package_single_order"),
    path('author/test/order/update/<int:id>', views.AuthorTestOrderUpdate, name="authorize_single_order_update"),
    path('author/package/order/update/<int:id>', views.AuthorPackageOrderUpdate, name="authorize_package_order_update"),



    # Archive pages

    path('author/test/orders/archive', views.AuthorTestOrderArchived.as_view(), name="authorize_test_order_archive"),
    path('author/package/orders/archive', views.AuthorPackageOrderArchived.as_view(), name="authorize_package_order_archive"),


    # Feedback and reviews urls mapping

    path('author/feedback', views.AuthorFeedback.as_view(), name="feedback"),
    path('author/review', views.AuthorReview.as_view(), name="review"),

    #REST API Home page url
    path('api', views.ApiHome.as_view(), name='api_home')
]

medical/models.py
from django.db import models
from accounts.models import patient
from django.urls import reverse
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.


class test_category(models.Model):
    name = models.CharField(max_length=200)
    details = models.TextField()

    def __str__(self):
        return self.name


class diagnostic_test(models.Model):
    name = models.CharField(max_length=200)
    category = models.ForeignKey(test_category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class hospital(models.Model):
    name = models.OneToOneField(User, on_delete=models.CASCADE)
    choice = (("Clinic", "Clinic"), ("Medical college", "Medical college"), ("Diagnostic center", "Diagnostic center"),
              ("Hospital", "Hospital"), ("Check up center", "Check up center"))
    type = models.CharField(choices=choice, max_length=200, default="Hospital")
    email = models.EmailField(max_length=200, default="")
    phone = models.CharField(max_length=200, default="")
    address = models.CharField(max_length=200)
    zip_code = models.CharField(max_length=20)
    div = (("Dhaka", "Dhaka"), ("Barishal", "Barishal"), ("Dinajput", "Dinajput"), ("Chittagong", "Chittagong"),
           ("Khulna", "Khulna"), ("Rajshahi", "Rajshahi"), ("Rangpur", "Rangpur"))
    division = models.CharField(choices=div, max_length=50)

    def __str__(self):
        return self.name.get_full_name()


class has_test(models.Model):
    name = models.ForeignKey(diagnostic_test, on_delete=models.CASCADE)
    hospital = models.ForeignKey(hospital, on_delete=models.CASCADE)
    test_details = RichTextUploadingField()
    price = models.IntegerField()
    delivary_in = models.IntegerField()
    is_home_deliverable = models.BooleanField(default=False)

    def __str__(self):
        return self.name.name

    def get_single_url(self):
        return reverse('medical:test_details', kwargs={"has_test_id": self.id})


class package(models.Model):
    name = models.CharField(max_length=200)
    hospital = models.ForeignKey(hospital, on_delete=models.CASCADE)
    details = RichTextUploadingField()
    price = models.IntegerField()
    delivary_in = models.IntegerField()
    remarks = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class package_item(models.Model):
    package_name = models.ForeignKey(package, on_delete=models.CASCADE)
    test = models.ManyToManyField(diagnostic_test)

    def __str__(self):
        return self.package_name.name


class ratings(models.Model):
    user = models.ForeignKey(patient, on_delete=models.CASCADE)
    test = models.ForeignKey(has_test, on_delete=models.CASCADE)
    r = (("Bad", "Bad"), ("Average", "Average"), ("Good", "Good"), ("Best", "Best"), ("Excellent", "Excellent"))
    rating = models.CharField(choices=r, max_length=15)
    comments = models.TextField()
    proof = models.ImageField()
    date = models.DateTimeField(auto_now=True, auto_now_add=False)
    aprove = models.BooleanField(default=False)

    def __str__(self):
        return self.test.name.name


class feedback(models.Model):
    user = models.ForeignKey(patient, on_delete=models.CASCADE)
    hospital = models.ForeignKey(hospital, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now=False, auto_now_add=True)
    comment = models.TextField()
    aprove = models.BooleanField(default=False)

    def __str__(self):
        return self.comment

    def __usr__(self):
        return self.user.name.username


class FeedbackReply(models.Model):
    feedbackTo = models.ForeignKey(feedback, on_delete=models.CASCADE)
    reply = models.TextField()
    date = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.feedbackTo.hospital.name.get_full_name()

order_billing/models.py
from django.db import models
from accounts.models import patient
from medical.models import has_test, package
from datetime import datetime

# Create your models here.
class Test_order(models.Model):
    user = models.ForeignKey(patient, on_delete=models.CASCADE)
    test = models.ForeignKey(has_test, on_delete=models.CASCADE)
    payment_status = models.CharField(max_length=20, default="Not Paid", choices=(
        ("Not Paid", "Not paid"), ("Partially Paid", "Partially Paid"), ("Fully Paid", "Fully Paid")))
    token_num = models.CharField(max_length=100, default="", blank=True, null=True)
    verify = models.BooleanField(default=False)
    is_completed = models.CharField(max_length=20, choices=(("Yes", "Yes"), ("No", "No")), default="No")
    test_taking_date = models.DateField(blank=True, null=True, default=datetime.now().date())
    test_taking_time = models.TimeField(blank=True, null=True, default=datetime.now().time())
    choice = (
        ("Processing", "Processing"), ("On hold", "On hold"), ("Completed", "Completed"), ("Refunded", "Refunded"),
        ("Archived", "Archived"))
    status = models.CharField(max_length=100, choices=choice, default="Processing")

    def __str__(self):
        return self.user.name.username


class Test_billing(models.Model):
    order = models.OneToOneField(Test_order, on_delete=models.CASCADE)
    paid_amount = models.IntegerField()
    account_number = models.CharField(max_length=100)
    transaction_id = models.CharField(max_length=100)
    paid_on = models.DateField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return "(" + str(self.order.id) + ") "

    def __patient__(self):
        return self.order.user.name.get_full_name()

    def __unicode__(self):
        return self.order.test.name


class Package_order(models.Model):
    user = models.ForeignKey(patient, on_delete=models.CASCADE)
    package_name = models.ForeignKey(package, on_delete=models.CASCADE)
    payment_status = models.CharField(max_length=20, default="Not Paid", choices=(
        ("Not Paid", "Not paid"), ("Partially Paid", "Partially Paid"), ("Fully Paid", "Fully Paid")))
    token_num = models.CharField(max_length=100, default="", blank=True, null=True)
    verify = models.BooleanField(default=False)
    test_taking_date = models.DateField(blank=True, null=True)
    test_taking_time = models.TimeField(blank=True, null=True)
    choice = (
        ("Processing", "Processing"), ("On hold", "On hold"), ("Completed", "Completed"), ("Refunded", "Refunded"),
        ("Archived", "Archived"))
    status = models.CharField(max_length=100, choices=choice, default="Processing")

    def __str__(self):
        return self.user.name.username


class Package_billing(models.Model):
    order = models.OneToOneField(Package_order, on_delete=models.CASCADE)
    paid_amount = models.IntegerField()
    account_number = models.CharField(max_length=100)
    transaction_id = models.CharField(max_length=100)
    paid_on = models.DateField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return "(" + str(self.order.id) + ") "

    def __patient__(self):
        return self.order.user.name.get_full_name()

    def __unicode__(self):
        return self.order.package_name.name

templates/dashboard/base_site.html
{% extends 'base.html' %}
{% block title %}{{ hospital.name.get_full_name }}{% endblock %}
{% block stylesheet %}
	<style>
	.main-content {
	margin-top: 64px;
	}
	nav{
	background-color: #1C2331!important;
	}
	span.info {
	position: absolute;
	text-align: justify;
	font-size: 20px;
	background: rgba(8, 193, 158, 0.58);
	height: 100%;
	color: #fff;
	width: 45%;
	}
	.container .row .col-md-3{
	margin-bottom:2px;
	}
	.inner i{
	padding: 5px;
	background: #5da30f;
	color: #fff;
	}
	body{
	background-color: #ecf0f5;
	}
	div#content {
	padding: 0px!important;
	}
    select.form-control:not([size]):not([multiple]) {
        height: auto;
    }
	</style>
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'css/style4.css' %}">
	<style>
	a[aria-expanded="false"]::before, a[aria-expanded="true"]::before {
	content: '';
	display: block;
	position: absolute;
	right: 20px;
	font-family: 'Glyphicons Halflings';
	font-size: 0.6em;
	}
	div#content {
	width: 100%;
	}
	tbody tr td a i{
	font-size: 24px!important;
	}
    table#my-table thead tr th a{
        color: #fff;
    }
    .breadcrumb ul li i {padding-left: 4px;}
    .breadcrumb ul li {display: inline-block;}
    .breadcrumb ul {list-style: none;}


    span.commenter{
        display: flex;
    }
    span.comment-text-action{
        display: none;
    }
    tr:hover td span.comment-text-action{
        display: block;
    }
	</style>
{% endblock %}
{% block content %}
	<div class="main-content">
		<div class="wrapper">
			<!-- Sidebar Holder -->
			<nav id="sidebar">
				<div class="sidebar-header">
					<a href="{% url 'medical:logged_hospital'%}">
						<h3>Admin Dashboard</h3>
						<strong>AD</strong>
					</a>
				</div>
				<ul class="list-unstyled components">
					<li class="test">
						<a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false">
							<i class="fa fa-stethoscope"></i>
							Tests
						</a>
						<ul class="collapse list-unstyled" id="homeSubmenu">
							{% if request.user.is_authenticated %}
								<li><a href="{% url 'medical:authorize_tests'%}">View Tests</a></li>
								<li><a href="{% url 'medical:authorize_test_add' %}">Add Test</a></li>
							{% endif %}
						</ul>
					</li>
					<li class="package">
						<a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false">
							<i class="fa fa-hospital-o"></i>
							Packages
						</a>
						<ul class="collapse list-unstyled" id="pageSubmenu">
							<li><a href="{% url 'medical:authorize_package_view'%}">View Packages</a></li>
							<li><a href="{% url 'medical:authorize_package_add' %}">Add package</a></li>
						</ul>
					</li>
					<li class="order">
						<a href="#orderSubmenu" data-toggle="collapse" aria-expanded="false">
							<i class="fa fa-shopping-cart"></i>
							Orders
						</a>
						<ul class="collapse list-unstyled" id="orderSubmenu">
							<li><a href="{% url 'medical:authorize_order' %}">Test</a></li>
							<li><a href="{% url 'medical:authorize_package_order' %}">Package</a></li>
						</ul>
					</li>
					<li class="archive">
						<a href="#archiveSubmenu" data-toggle="collapse" aria-expanded="false">
							<i class="fa fa-archive"></i>
							Archived orders
						</a>
						<ul class="collapse list-unstyled" id="archiveSubmenu">
							<li><a href="{% url 'medical:authorize_test_order_archive' %}">Test</a></li>
							<li><a href="{% url 'medical:authorize_package_order_archive' %}">Package</a></li>
						</ul>
					</li>
				</ul>
				<ul class="list-unstyled CTAs">
					<li class="feedback"><a href="{% url 'medical:feedback' %}">Feedback</a></li>
					<li class="review"><a href="{% url 'medical:review' %}">Reviews</a></li>
				</ul>
			</nav>
			<!-- Page Content Holder -->
			<div id="content">
				<nav class="navbar navbar-default" style="background: #3f8b9c!important;">
					<div class="container-fluid">
						<div class="navbar-header">
							<button type="button" id="sidebarCollapse" class="btn btn-info navbar-btn">
							<i class="fa fa-align-left fa-2x"></i>
							</button>
						</div>
						<div class="breadcrumb" style="color: white">
							{% block breadcrumb %}
							{% endblock %}
						</div>
					</div>
				</nav>
				<div class="container">
					{% block dashboardcontent %}
					{% endblock %}
				</div>
			</div>
		</div>
	</div>
{% endblock %}
{% block script %}
	<script type="text/javascript">
	$(document).ready(function() {
	    $('#sidebarCollapse').on('click', function() {
	        $('#sidebar').toggleClass('active');
	    });
	});
	</script>
{% endblock %}

templates/dashboard/form.html
{% extends 'dashboard/base_site.html' %}
{% block title %}
	{{ title }}
{% endblock %}
{% block breadcrumb %}
    <ul>
    {% if request.get_full_path == "/author/package/add" %}
    <li><a href="{% url 'medical:logged_hospital' %}">Dashboard<i class="fa fa-chevron-circle-right"></i></a></li>
    <li><a href="{% url 'medical:authorize_package_view' %}">View packages<i class="fa fa-chevron-circle-right"></i></a></li><li>Add Package</li>
        {% elif request.get_full_path == "/author/test/add" %}
        <li><a href="{% url 'medical:logged_hospital' %}">Dashboard<i class="fa fa-chevron-circle-right"></i></a></li>
        <li><a href="{% url 'medical:authorize_tests' %}">View tests<i class="fa fa-chevron-circle-right"></i></a></li><li>Add Test</li>
    {% endif %}
    </ul>
{% endblock %}
{% block dashboardcontent %}
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            {{ message }}</div>
        {% endfor %}
    </ul>
    {% endif %}
	<div class="container wow fadeIn">
		<form action="" method="POST">
			{% csrf_token %}
            {{ form.media }}
			{{ form.as_p }}
			<button class="btn btn-primary">{{ btnTxt }}</button>
		</form>
	</div>
{% endblock %}
{% block script %}
	<script>
	$(document).ready(function() {
	    $('form p').addClass('input-group row');
	    $('label').addClass('col-md-3');
	    $('input').addClass('form-control col-md-9');
	    $('textarea').addClass('form-control col-md-9');
	    $('select').addClass('form-control');
	    $("#nav-search").removeClass('col-md-9');
	    $('input#id_verify').removeClass('col-md-9 form-control');
	    $('input#id_is_home_deliverable').removeClass('col-md-9 form-control');
	});
	</script>
{% endblock %}

templates/dashboard/view_orders.html
{% extends 'dashboard/base_site.html' %}
{% block title %}
	All orders
{% endblock %}
{% block breadcrumb %}
	<ul>
        <li><a href="{% url 'medical:logged_hospital' %}">Dashboard<i class="fa fa-chevron-circle-right"></i></a></li>
        <li><a href="">Orders<i class="fa fa-chevron-circle-right"></i></a></li>
        {% if type == 'test' %}
            <li><a href="">Test</a></li>
            {% elif type == 'package' %}
            <li><a href="">Package</a></li>
        {% endif %}
    </ul>
{% endblock %}
{% block dashboardcontent %}
	<div class="container wow fadeIn">
		{% if type == "test" %}
            <div class="order-btn" style="text-align: right;"><a href="{% url 'medical:authorize_package_order' %}" class="btn btn-brown">View package order</a></div>
            <!--Table-->
            <table id="my-table" class="table table-bordered">
                <!--Table head-->
                <thead class="mdb-color darken-3">
                    <tr class="text-white">
                        <th>#</th>
                        <th>Patient</th>
                        <th>Test</th>
                        <th>Contact</th>
                        <th>Payment status</th>
                        <th></th>
                    </tr>
                </thead>
                <!--Table head-->
                <!--Table body-->
                <tbody>
                    {% for order in orders %}
                        {% if order.status != 'Archived' %}
                            <tr>
                                <th scope="row">{{ order.id }}</th>
                                <td>{{ order.user.name.username }}</td>
                                <td>{{ order.test.name.name }}</td>
                                <td>{{ order.user.phone }}</td>
                                <td>{% if order.payment_status == "Not Paid" %}
                                    <label class="alert-danger">{{ order.payment_status }}</label>
                                    {% elif order.payment_status == "Partially Paid" %}
                                    <label class="alert-warning">{{ order.payment_status }}</label>
                                    {% else %}
                                    <label class="alert-success">{{ order.payment_status }}</label>
                                {% endif %}</td>
                                <td><a href="{% url 'medical:authorize_single_order' id=order.id %}">View details</a></td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
                <!--Table body-->
            </table>
            <!--Table-->
            {% elif type == "package" %}
            <!--Table-->
            <div class="order-btn" style="text-align: right;"><a href="{% url 'medical:authorize_order' %}" class="btn btn-brown">View test order</a></div>
            <table id="my-table" class="table table-bordered">
                <!--Table head-->
                <thead class="mdb-color darken-3">
                    <tr class="text-white">
                        <th>#</th>
                        <th>Patient</th>
                        <th>Package</th>
                        <th>Contact</th>
                        <th>Payment status</th>
                        <th></th>
                    </tr>
                </thead>
                <!--Table head-->
                <!--Table body-->
                <tbody>
                    {% for order in orders %}
                        {% if order.status != 'Archived' %}
                            <tr>
                                <th scope="row">{{ order.id }}</th>
                                <td>{{ order.user.name.username }}</td>
                                <td>{{ order.package_name.name }}</td>
                                <td>{{ order.user.phone }}</td>
                                <td>{% if order.payment_status == "Not Paid" %}
                                    <label class="alert-danger">{{ order.payment_status }}</label>
                                    {% elif order.payment_status == "Partially Paid" %}
                                    <label class="alert-warning">{{ order.payment_status }}</label>
                                    {% else %}
                                    <label class="alert-success">{{ order.payment_status }}</label>
                                {% endif %}</td>
                                <td><a href="{% url 'medical:authorize_package_single_order' id=order.id %}">View details</a></td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
                <!--Table body-->
            </table>
            <!--Table-->
		{% endif %}
	</div>
{% endblock %}
{% block script %}
    {% load staticfiles %}
   <link rel="stylesheet" href="{% static 'css/jquery.dynatable.css' %}">
    <script src="{% static 'js/jquery.dynatable.js' %}"></script>
    <script>
    $(document).ready(function() {
	    $('.order').addClass('active');
	});
    $('#my-table').dynatable({
    table: {
    defaultColumnIdStyle: 'trimDash'
    }
    });
    </script>
{% endblock %}

templates/dashboard/view_package.html
{% extends 'dashboard/base_site.html' %}
{% block title %}
	{{ request.user.get_full_name }} || Packages
{% endblock %}
{% block breadcrumb %}
	<ul>
        <li><a href="{% url 'medical:logged_hospital' %}">Dashboard<i class="fa fa-chevron-circle-right"></i></a></li>
        <li>Package</li>
    </ul>
{% endblock %}
{% block dashboardcontent %}
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            {{ message }}</div>
        {% endfor %}
    </ul>
    {% endif %}
	<div class="wow fadeIn">
        <div class="all-packages">
            <div class="row">
                {% if items is None %}
                    <div class="col-md-12">
                        <div class="package-add" style="text-align: right">
                            <a href="{% url 'medical:authorize_package_add' %}" class="btn btn-primary">+Add</a>
                        </div>
                        <table id="my-table" class="table table-bordered">
                            <thead>
                                <tr style="background: #0f3829;">
                                    <th>Package Name</th>
                                    <th>Price</th>
                                    <th></th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for pack in package %}
                                    <tr>
                                        <td>{{ pack.name }}</td>
                                        <td>{{ pack.price }}</td>
                                        <td><a href="{% url 'medical:authorize_package_view' %}?p={{ pack.id }}">View Items</a></td>
                                        <td>
                                            <a href="{% url 'medical:authorize_package_update' id=pack.id %}" class="text-success"><i class="fa fa-pencil-square"></i></a>
                                            <a href="" class="text-danger" data-toggle="modal" data-target="#exampleModal" onclick="deletePackage({{ pack.id }})"><i class="fa fa-trash"></i></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                {% else %}
                    <div class="col-md-8">
                        <div class="package-add" style="text-align: right">
                            <a href="{% url 'medical:authorize_package_add' %}" class="btn btn-primary">+Add</a>
                        </div>
                        <table id="my-table" class="table table-bordered">
                            <thead>
                                <tr style="background: #0f3829;">
                                    <th>Package Name</th>
                                    <th>Price</th>
                                    <th></th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for pack in package %}
                                    <tr>
                                        <td>{{ pack.name }}</td>
                                        <td>{{ pack.price }}</td>
                                        <td><a href="{% url 'medical:authorize_package_view' %}?p={{ pack.id }}">View Items</a></td>
                                        <td>
                                            <a href="{% url 'medical:authorize_package_update' id=pack.id %}" class="text-success"><i class="fa fa-pencil-square"></i></a>
                                            <a href="" class="text-danger" data-toggle="modal" data-target="#exampleModal" onclick="deletePackage({{ pack.id }})"><i class="fa fa-trash"></i></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="col-md-4">
                        <h3>Package items</h3>
                        {% if items %}
                            <ul>
                                {% for item in items %}
                                    {% for i in item.test.all %}
                                        <li>{{ i }}</li>
                                        {% empty %}
                                        <h1>Sorry! No items found</h1>
                                    {% endfor %}
                                    {% empty %}
                                    <h1>Sorry! No items found</h1>
                                {% endfor %}
                            </ul>
                            <a href="{% url 'medical:authorize_package_item_update' id=packid %}" class="btn btn-blue-grey">Update items</a>
                        {% else %}
                            <a href="{% url 'medical:authorize_package_item_add' id=packid %}" class="btn btn-success">Add Items</a>
                        {% endif %}
                    </div>
                {% endif %}
            </div>
        </div>
	</div>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Delete Package</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div class="inf"></div>
                        <input type="hidden" name="package" class="modal-input" id="pack-id" value="">
                        <label for="pass">Re-enter password:</label>
                        <input type="password" name="password" class="form-control" id="pass">
                    </div>
                    <div class="modal-footer">
                        <a class="btn btn-secondary" data-dismiss="modal">Close</a>
                        <button class="btn btn-primary" id="deleteBtn">Delete</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
{% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/jquery.dynatable.css' %}">
    <script src="{% static 'js/jquery.dynatable.js' %}"></script>
    <script>
    $(document).ready(function() {
        $('.package').addClass('active');

        $('button#deleteBtn').click(function (e) {
            if ($('input#pass').val()==="") {
                $('#pass').addClass('is-invalid');
                $('.inf').html('<p class="text-danger">Password is required</p>');
                e.preventDefault();
            }
        });
	});
    $('#my-table').dynatable({
        table: {defaultColumnIdStyle: 'trimDash'}
    });

    function deletePackage(x) {
        $('input#pack-id').attr('value', x);
    }
    </script>
{% endblock %}